### obtener todos los pedidos
GET http://localhost:3000/api/pedidos


### obtener un unico pedido
GET http://localhost:3000/api/pedidos/2


### crear un pedido
POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "modalidad": "COMER EN HAMBURGUESERIA",
    "montoTotal":100 ,
    "estado": "EN PROCESO",
    "idCliente": 3,
    "hamburguesas": [
        {
            "idHamburguesa": 3,
            "cantidad": 1400
        },
        {
            "idHamburguesa": 2,
            "cantidad": 100
        }
    ]
}

### modificar un pedido
PUT http://localhost:3000/api/pedidos/2
Content-Type: application/json

{
    "modalidad": "COMER EN HAMBURGUESERIA",
    "montoTotal": 5,
    "estado": "EN PROCESO",
    "idCliente": 3,
    "hamburguesas": [
        {
            "idHamburguesa": 1,
            "cantidad": 1
        },
        {
            "idHamburguesa": 2,
            "cantidad": 2
        }
    ]
}


### modificar un pedido con PATCH
PATCH http://localhost:3000/api/pedidos/4
Content-Type: application/json

{
    "modalidad": "Queso",
    "montoTotal": 5,
    "estado": "EN PROCESO",
    "idCliente": 2,
    "hamburguesas": [
        {
            "idHamburguesa": 1,
            "cantidad": 2
        }
    ]
}

### borrar un pedido
DELETE http://localhost:3000/api/pedidos/13

### Cambiar estado
PUT http://localhost:3000/api/pedidos/2/estado
Content-Type: application/json

{
    "estado": "ENTREGADO"
}

